import sanitizeHtml from "sanitize-html";
import { deepmerge } from "deepmerge-ts";
import { site } from "astro:config/client";

const tailwindProseSanitizeConfig = {
  allowedClasses: {
    p: ["lead"],
  },
  allowedAttributes: {
    // Allow heading IDs generated by `rehype-slug`
    h1: ["id"],
    h2: ["id"],
    h3: ["id"],
    h4: ["id"],
    h5: ["id"],
    h6: ["id"],
  },
} satisfies sanitizeHtml.IOptions;

const shikiSanitizeConfig = {
  allowedTags: [],
  allowedClasses: {
    pre: [
      "shiki",
      // https://shiki.style/themes#bundled-themes
      "andromeeda",
      "aurora-x",
      "ayu-dark",
      "catppuccin-frappe",
      "catppuccin-latte",
      "catppuccin-macchiato",
      "catppuccin-mocha",
      "dark-plus",
      "dracula",
      "dracula-soft",
      "everforest-dark",
      "everforest-light",
      "github-dark",
      "github-dark-default",
      "github-dark-dimmed",
      "github-dark-high-contrast",
      "github-light",
      "github-light-default",
      "ithub-light-high-contrast",
      "houston",
      "kanagawa-dragon",
      "kanagawa-lotus",
      "kanagawa-wave",
      "laserwave",
      "light-plus",
      "material-theme",
      "material-theme-darker",
      "material-theme-lighter",
      "material-theme-ocean",
      "material-theme-palenight",
      "min-dark",
      "min-light",
      "monokai",
      "night-owl",
      "nord",
      "one-dark-pro",
      "one-light",
      "plastic",
      "poimandres",
      "red",
      "rose-pine",
      "rose-pine-dawn",
      "rose-pine-moon",
      "slack-dark",
      "slack-ochin",
      "snazzy-light",
      "solarized-dark",
      "solarized-light",
      "synthwave-84",
      "tokyo-night",
      "vesper",
      "vitesse-black",
      "vitesse-dark",
      "vitesse-light",
    ],
    span: ["line"],
  },
  allowedAttributes: {
    pre: ["style"],
    span: ["style"],
  },
} satisfies sanitizeHtml.IOptions;

const iframeSanitizeConfig = {
  allowedTags: ["iframe"],
  allowedIframeDomains: [
    // Allow configured Astro site if it exists
    ...(site ? [new URL(site).hostname] : []),
    // Allow localhost for development
    "localhost",
    "youtube-nocookie.com",
    "youtube.com",
  ],
  allowedAttributes: {
    iframe: [
      "title",
      "src",
      "width",
      "height",
      "frameborder",
      "allow",
      "allowfullscreen",
      "sandbox",
    ],
  },
  transformTags: {
    // Sandbox iframes
    // See: https://stackoverflow.com/q/68274122/1865857
    // See: https://dev.to/patarapolw/securely-embed-youtube-and-other-iframe-elements-in-markdown-2hoc
    iframe: sanitizeHtml.simpleTransform("iframe", {
      sandbox: "allow-same-origin allow-scripts allow-presentation",
    }),
  },
} satisfies sanitizeHtml.IOptions;

function sanitize(html: string): string {
  return sanitizeHtml(
    html,
    deepmerge(
      sanitizeHtml.defaults,
      shikiSanitizeConfig,
      tailwindProseSanitizeConfig,
      iframeSanitizeConfig,
      {
        allowedTags: ["img", "video", "source"],
        allowedAttributes: {
          video: ["preload", "controls", "width", "height"],
          source: ["src", "type"],
        },
      } satisfies sanitizeHtml.IOptions,
    ),
  );
}

export { sanitize as sanitizeHtml };
