# Production compose file for Astro
#
# We're using `docker-compose.yaml` instead of just `Dockerfile` so that we can
# define `ENV` variables that are automatically shown in Coolify UI as well as
# include a separate `docker-compose.test.yaml` that can be used to test the
# image locally.

services:
  frontend-astro:
    build:
      context: .
      args:
        PUBLIC_DIRECTUS_URL: ${PUBLIC_DIRECTUS_URL}
        PUBLIC_ASTRO_SITE: ${PUBLIC_ASTRO_SITE}
    restart: unless-stopped
    expose:
      - 80
    environment:
      # Uses Coolify's `${VAR}` syntax to add editable variables to UI. See:
      # https://coolify.io/docs/knowledge-base/docker/compose#defining-environment-variables
      #
      # NOTE - These variable variables must be overridden in `.env` for
      # development. See `.env.example` for more.
      PUBLIC_DIRECTUS_URL: ${PUBLIC_DIRECTUS_URL}
      PUBLIC_ASTRO_SITE: ${PUBLIC_ASTRO_SITE}
